Grid
dipen2000/zest-ui pull request #10
Opened 2022-02-10 19:21 UTC by dipen2000

I created this grid component, please review my PR and give feedback.

2022-02-10 19:31 UTC, rahulyadav139 approved these changes

2022-02-10 19:31 UTC, rahulyadav139 commented on components/Grid/grid.css
> +}
ideally, you should have written 7fr 3fr for 70-30 grid and 3fr 7fr for 30-70 grid. class naming is simple and elegant.

2022-02-11 07:02 UTC, kushalsourav commented
make navigation sticky it would be good

2022-02-11 12:49 UTC, abhishektanwar requested changes

2022-02-11 12:49 UTC, abhishektanwar commented on CSS/documentation.css
> +
please remove comments

2022-02-11 12:49 UTC, abhishektanwar commented on CSS/documentation.css
> +    background-color : rgba(102, 51, 153, 0.356);
Try to remain consistent when using colors. Use variables , this will increase code readability

2022-02-11 12:49 UTC, abhishektanwar commented on CSS/documentation.css
> +    height : 580px;
relative units could be used here.

2022-02-19 10:58 UTC, j24m approved these changes
Hey, please resolve all the conversations before merging, some older comments contain changes suggested by others, you must make those changes, that is the whole purpose of the code review:) , remove commented code, provide with proper indentation by using beautify or some other extension, use color variable at all places and then you are good to go :)

2022-02-20 12:37 UTC, merged