Avatar badge
dipen2000/zest-ui pull request #2
Opened 2022-02-09 20:34 UTC by dipen2000

Created avatar and badge components from the component library , please review my PR.

2022-02-09 21:24 UTC, dhimanaishwarya requested changes

2022-02-09 21:24 UTC, dhimanaishwarya commented on CSS/documentation.css
> +    background-color : rgba(102, 51, 153, 0.356);
use variable for color everywhere

2022-02-09 21:24 UTC, dhimanaishwarya commented on CSS/documentation.css
> +    border-bottom-right-radius: 15px;
above 10px you can use rem unit

2022-02-09 21:24 UTC, dhimanaishwarya commented on components/avatar/avatar.html
> +                        <p class="mb-2">These are all the rounded same sized buttons</p>
documentation to be corrected here

2022-02-09 21:24 UTC, dhimanaishwarya commented on CSS/documentation.css
> +    /* font-size: 4rem; */
remove comments which are not required

2022-02-09 21:24 UTC, dhimanaishwarya commented on components/avatar/avatar.html
> +                        <section class="component-scetion mb-2">
typo in the class name , also if you are not using this class you can remove it

2022-02-09 21:28 UTC, dhimanaishwarya commented
UI looks good

2022-02-10 09:38 UTC, rahulyadav139 approved these changes

2022-02-10 09:38 UTC, rahulyadav139 commented on CSS/documentation.css
> +    font-size: 2rem;
everything is great, use rem instead of px.

2022-02-10 10:00 UTC, dev-ashishsethi approved these changes
looks good

2022-02-10 10:00 UTC, dev-ashishsethi commented on prism/prism.css
> +  color: inherit;
looks good to me you can merge

2022-02-10 13:14 UTC, j24m approved these changes
Good work bro , code seems more than good and UI too. GTM!! :)

2022-02-10 14:52 UTC, m26unkwn approved these changes
GTM

2022-02-10 14:52 UTC, m26unkwn commented on components/badges/badge.css
> +
This is too good to be true you are simplifying it.

2022-02-20 12:28 UTC, merged